const router=require('express').Router();const crypto=require('crypto');const {z}=require('zod');const db=require('../db');const {authenticate,permit}=require('../middleware/auth');const {postJournal}=require('../services/accounting');
router.use(authenticate,permit('manager','accountant','admin'));
router.get('/trial-balance',async(req,res,next)=>{try{const asOf=z.coerce.date().catch(new Date()).parse(req.query.asOf);const {rows}=await db.query(`SELECT a.code,a.name,a.type,COALESCE(SUM(jl.debit) FILTER(WHERE je.id IS NOT NULL),0) debit,COALESCE(SUM(jl.credit) FILTER(WHERE je.id IS NOT NULL),0) credit,COALESCE(SUM(jl.debit-jl.credit) FILTER(WHERE je.id IS NOT NULL),0) balance FROM accounts a LEFT JOIN journal_lines jl ON jl.account_id=a.id LEFT JOIN journal_entries je ON je.id=jl.journal_entry_id AND je.entry_date<=$2 WHERE a.organization_id=$1 GROUP BY a.id ORDER BY a.code`,[req.user.organizationId,asOf]);res.json({asOf,totalDebit:rows.reduce((s,r)=>s+Number(r.debit),0),totalCredit:rows.reduce((s,r)=>s+Number(r.credit),0),data:rows})}catch(e){next(e)}});
router.get('/general-ledger',async(req,res,next)=>{try{const q=z.object({from:z.coerce.date(),to:z.coerce.date(),accountId:z.string().uuid().optional()}).parse(req.query);const {rows}=await db.query(`SELECT je.entry_number,je.entry_date,je.description,je.source_type,je.source_id,a.code,a.name,jl.debit,jl.credit,u.name posted_by,je.posted_at FROM journal_entries je JOIN journal_lines jl ON jl.journal_entry_id=je.id JOIN accounts a ON a.id=jl.account_id JOIN users u ON u.id=je.posted_by WHERE je.organization_id=$1 AND je.entry_date BETWEEN $2 AND $3 AND ($4::uuid IS NULL OR a.id=$4) ORDER BY je.entry_date,je.entry_number,jl.id LIMIT 5000`,[req.user.organizationId,q.from,q.to,q.accountId||null]);res.json({data:rows})}catch(e){next(e)}});
router.post('/journals',async(req,res,next)=>{try{const input=z.object({date:z.coerce.date(),description:z.string().min(5).max(300),lines:z.array(z.object({accountId:z.string().uuid(),debit:z.number().min(0).default(0),credit:z.number().min(0).default(0)})).min(2).max(100)}).parse(req.body);const journal=await db.transaction(client=>postJournal(client,{organizationId:req.user.organizationId,date:input.date,description:input.description,sourceType:'manual',sourceId:crypto.randomUUID(),userId:req.user.sub,lines:input.lines}));res.status(201).json({journal})}catch(e){next(e)}});
router.get('/profit-loss',async(req,res,next)=>{try{const q=z.object({from:z.coerce.date(),to:z.coerce.date()}).parse(req.query);const {rows}=await db.query(`SELECT a.code,a.name,a.type,SUM(jl.credit-jl.debit) amount FROM accounts a JOIN journal_lines jl ON jl.account_id=a.id JOIN journal_entries je ON je.id=jl.journal_entry_id WHERE a.organization_id=$1 AND a.type IN ('revenue','cogs','expense') AND je.entry_date BETWEEN $2 AND $3 GROUP BY a.id ORDER BY a.code`,[req.user.organizationId,q.from,q.to]);const revenue=rows.filter(x=>x.type==='revenue').reduce((s,x)=>s+Number(x.amount),0),costs=rows.filter(x=>x.type!=='revenue').reduce((s,x)=>s-Number(x.amount),0);res.json({from:q.from,to:q.to,revenue,costs,netProfit:revenue-costs,data:rows})}catch(e){next(e)}});
router.get('/balance-sheet',async(req,res,next)=>{try{const asOf=z.coerce.date().parse(req.query.asOf);const {rows}=await db.query(`SELECT a.code,a.name,a.type,SUM(CASE WHEN a.type='asset' THEN jl.debit-jl.credit ELSE jl.credit-jl.debit END) amount FROM accounts a JOIN journal_lines jl ON jl.account_id=a.id JOIN journal_entries je ON je.id=jl.journal_entry_id WHERE a.organization_id=$1 AND a.type IN ('asset','liability','equity') AND je.entry_date<=$2 GROUP BY a.id ORDER BY a.code`,[req.user.organizationId,asOf]);res.json({asOf,data:rows})}catch(e){next(e)}});
router.get('/vat-return',async(req,res,next)=>{try{const q=z.object({from:z.coerce.date(),to:z.coerce.date()}).parse(req.query);const {rows}=await db.query(`SELECT a.code,a.name,SUM(jl.credit-jl.debit) balance FROM accounts a JOIN journal_lines jl ON jl.account_id=a.id JOIN journal_entries je ON je.id=jl.journal_entry_id WHERE a.organization_id=$1 AND a.code IN ('1400','2100') AND je.entry_date BETWEEN $2 AND $3 GROUP BY a.id ORDER BY a.code`,[req.user.organizationId,q.from,q.to]);res.json({period:q,data:rows})}catch(e){next(e)}});
module.exports=router;
